// <auto-generated />
using LaBonneAuberge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaBonneAuberge.Migrations
{
    [DbContext(typeof(LaBonneAubergeContext))]
    [Migration("20231229112234_FeedBack")]
    partial class FeedBack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LaBonneAuberge.Models.FeedBackModel", b =>
                {
                    b.Property<int>("Id_FeedBack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email_FeedBack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message_FeedBack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Notation_FeedBack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pseudo_FeedBack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_FeedBack");

                    b.ToTable("FeedBacks");
                });
#pragma warning restore 612, 618
        }
    }
}
